### ISSUE TITLE
about error when executing the afl-fuzz

### ISSUE THREAD

**Issue by minifish120** [aerosec/jetset_fuzzer#1]
when I run the command : 
sudo ./runall.sh -q arm-softmmu/qemu-system-arm -c "-Wno-error -DSYNTH_ENABLED=1" -s "afl-qemu-scripts/afl-qemu-trace-synth-cmu"

it shows the error, listing as follows:

LINK    arm-softmmu/qemu-system-arm
COPYING TRACE
*************************************************

*************************************************
MAKING DIRECTORIES FOR f0
afl-fuzz 2.54b by <lcamtuf@google.com>
[+] You have 4 CPU cores and 3 runnable tasks (utilization: 75%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #2.
[*] Checking core_pattern...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning './testcases/others/syscall/'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id:000000,orig:testcase'...
[*] Spinning up the fork server...
AFL ENTRY SET 1033734afl-qemu: -drive if=pflash,format=raw,index=0,file=./data/cmu/boot.bin: Could not open './data/cmu/boot.bin': No such file or directory

So, can you tell me what's the meaning of the afl-qemu-scripts/afl-qemu-trace-synth-cmu?  And, how should i prepapre the items in ./data ?

Thanks for your attentation!

**Comment by maxwell-bland** [comment]
afl-qemu-scripts/afl-qemu-trace-synth-cmu is the qemu command line that AFL runs at each instantiation of a child process for fuzzing. This is copied into "afl-qemu" in the afl directory by the runall.sh script. The failures of opening "data" are because these are the flash files for the Boeing 737 CMU900, which I have not made public. In  afl-qemu-scripts/afl-qemu-trace-synth-cmu you will also see custom flags I've added for specifying "files to checkpoint" for the fuzzer. This is because some flash devices, when used with a file backing inside of QEMU, become modified by the child. The specification of these files to the qemu command line tells the fuzzer to restore these files with every run of the fuzzer.

I know, this is a bit complicated due to QEMU's method of handling these OS objects, but it is the best way I found to handle file-mapped flash while maintaining minimal changes to the QEMU source code.

While YAFL is still a WIP (we have one more bug relating to timing that we are squashing before the first release), the implementation is much simpler and should give great insight into how this initial (and fast, working) version of the fuzzer is implemented. See github.com/maxwell-bland/yafl

**Comment by minifish120** [comment]
Thanks for your reply.


But i'm still wondered by the meaning of the items in the 'data'. If I want to fuzz the drone (from the jetset_public_data) with the jetset_fuzzer or your yafl,  what should i prepare to the directory "data"? That's to say, what should i do if i want to fuzz the drone in jetset_public_data/p2im_firmware/Drone?  Can you show me the steps about how to fuzz a general firmware with the tool? 


Thanks very much for your attention!





On 2/9/2022 00:38，Maxwell ***@***.***> wrote：

afl-qemu-scripts/afl-qemu-trace-synth-cmu is the qemu command line that AFL runs at each instantiation of a child process for fuzzing. This is copied into "afl-qemu" in the afl directory by the runall.sh script. The failures of opening "data" are because these are the flash files for the Boeing 737 CMU900, which I have not made public. In afl-qemu-scripts/afl-qemu-trace-synth-cmu you will also see custom flags I've added for specifying "files to checkpoint" for the fuzzer. This is because some flash devices, when used with a file backing inside of QEMU, become modified by the child. The specification of these files to the qemu command line tells the fuzzer to restore these files with every run of the fuzzer.

I know, this is a bit complicated due to QEMU's method of handling these OS objects, but it is the best way I found to handle file-mapped flash while maintaining minimal changes to the QEMU source code.

While YAFL is still a WIP (we have one more bug relating to timing that we are squashing before the first release), the implementation is much simpler and should give great insight into how this initial (and fast, working) version of the fuzzer is implemented. See github.com/maxwell-bland/yafl

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by maxwell-bland** [comment]
> I've added for specifying "files to checkpoint" for the fuzzer. This is because some flash devices, when used with a file backing inside of QEMU, become modified by the child. The specification of these files to the qemu command line tells the fuzzer to restore these files with every run of the fuzzer.

That is the meaning of the data flags. For the drone, it does not do any self-unpacking or modification of the flash backing image, so you do not need the data flags.

**Comment by maxwell-bland** [comment]
In terms of fuzzing a general firmware, there is a one hour video tutorial posted into the README.md, one README.md in the root of this repository, a second in the `afl/` directory, and one in the yafl repository. The core concept behind all of these is the same. You should check out the `example` directory for code that you could copy-paste (of course, for the drone, this will require some modification).

For fuzzing the drone, you may consider fuzzing values returned from the API calls to read from serial, the gyroscope, etc.. These function calls can be found using ghidra pretty easily because the P2IM paper and other work in this area used non-symbol-stripped firmware.

This is actually the reason Jetset is more complicated to use: it is the only work I know of in this area that analyzed real, symbol-stripped binaries (the SEL feeder relay and the CMU), though reviewers made us also evaluate the P2IM targets for completeness. Handling this diverse array of targets required a novel fuzzing architecture (what you see before you) and deeper modifications to how QEMU handles the TCG IR.
