### ISSUE TITLE
Some problem on fuzzing

### ISSUE THREAD

**Issue by bob81135** [aerosec/jetset_fuzzer#2]
hi, I have some problem for fuzzing.
first, I follow this video [here](https://youtu.be/mJYM7Z_c8e0).
I get the pc information on Drone, but I don't know how to next step.
Can you show me the steps about how to fuzz Drone. Thank you.

**Comment by maxwell-bland** [comment]
Hi, 

To fuzz the drone, begin by identifying (1) some portion of the drone's execution you desire to fuzz, e.g. gyroscope input. Once you have the specific program counter and system state identified (e.g. a set of memory addresses to write fuzzed input to, or registers), you can supply fuzzer input to these state values by making a call to read fuzzer input:

See https://github.com/aerosec/jetset_fuzzer/blob/82dd5687c8cbc85edf6d41ec81c92a91e014131a/example/cpu-exec.c#L162

 (2) making sure that your emulation reaches that PC value in the code, that is, jetset is able to infer a path to that point in the execution
 
 Likely a reverse engineering tool such as the NSA's Ghidra (https://ghidra-sre.org/) will help with this process.
 
 (3) Set up the code and recompile the docker container as suggested by the readme; you will need to set up the commandlines for the fuzzer to run qemu (see how https://github.com/aerosec/jetset_fuzzer/blob/master/afl/afl-qemu-scripts/afl-qemu-trace-oracle-cmu is used in the current repo for an example).
 
 (4) Use the https://github.com/aerosec/jetset_fuzzer/blob/master/scripts/afl-fuzz-one.sh script to run an instance of the fuzzer.
 
Hopefully that helps, and stay tuned to the yAFL repository as well. I am working on a few other projects right now, but fixing the timer issues in the new version of qemu used by yAFL is on my todo list. Moreover, also try my sequel to this project, yAFL. I've significantly refactored the code and it is in a (mostly) working state. I believe some of the timing issues in yAFL may only be due to timers affecting the virtual device interface, and basic fuzzing will work in most scenarios.

Cheers,
M
